### ISSUE TITLE
Custom lints not showing lints at all

### ISSUE THREAD

**Issue by Biplab-Dutta** [invertase/dart_custom_lint#36]
So, I was working on some lints and everything was fine until yesterday. I created my lint, had it working and then I went saved my work, and went to bed. The next day when I tried opening the same project, the lints are not getting displayed at all. I had other lint projects too and none of them are working. I have all the `dependencies` and `dev_dependencies` properly configured.

**Comment by Biplab-Dutta** [comment]
After taking a look at the internals of `custom_lint` package, I saw an error in the `analyzer_plugin.dart` file.
![image](https://user-images.githubusercontent.com/63902683/193470183-f6317b7e-96a6-4f75-9ac2-040e81f23417.png)

The error message says
```
The named parameter 'cacheTime' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'cacheTime'.
```
Can this be the reason why the lints which were working fine stopped getting displayed?

**Comment by rrousselGit** [comment]
Run `pub upgrade` and this should be fixed now.

**Comment by Biplab-Dutta** [comment]
@rrousselGit Looks like the issue still exists.
This is the `pubspec.yaml` of my sample lint project.
```yaml
name: sample_lints
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  analyzer: ^4.6.0
  analyzer_plugin: ^0.10.0
  custom_lint_builder: ^0.0.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
```
On running `dart run custom_lint`, I am getting proper logs
```bash
lib/hello_world.dart:5:7 • Classes extending Mock or Fake should be private and be at the bottom of the file. • create_private_mock_or_fake_class_and_move_declaration_to_bottom
lib/hello_world.dart:7:7 • Classes extending Mock or Fake should be at the bottom. • move_mocks_and_fakes_to_the_bottom_of_the_file
lib/hello_world.dart:9:7 • Classes extending Mock or Fake should be private and be at the bottom of the file. • create_private_mock_or_fake_class_and_move_declaration_to_bottom
lib/second_file.dart:3:7 • Classes extending Mock or Fake should be private and be at the bottom of the file. • create_private_mock_or_fake_class_and_move_declaration_to_bottom
```
However, the IDE doesn't show any warnings.
![image](https://user-images.githubusercontent.com/63902683/193847110-59dfcdfa-2374-4e29-ac03-d07e03aedbfd.png)

The `analyzer` and `analyzer_plugin` can be upgraded to ^5.1.0 and ^0.11.2 respectively. But `custom_lint` still depends on older version.

**Comment by rrousselGit** [comment]
I'll look into it tomorrow.

**Comment by rrousselGit** [comment]
This should be good to go now. Make sure to upgrade all your dependencies to latest.

If you still have the issue, please open a new issue (as this one is closed).

**Comment by AdamNSmith** [comment]
That fixed it. Thanks @rrousselGit!

**Comment by alexisbg** [comment]
@rrousselGit Thank you for the update but there is still an issue for me.

This time custom_lint.log is filled by my prints but the VSCode Problem panel is stuck on this warning:
`The plugin is currently starting dart(custom_lint_plugin_loading)`

![custom_lint_plugin_loading_50%](https://user-images.githubusercontent.com/5768935/194703545-a4e77b55-754a-4e5d-8d40-1b9a6c4d582b.png)

Here is what i am using:
- VSCode (WSL) 1.71.2
- Dart SDK 2.18.2
- custom_lint 0.0.12
- analyzer 4.7.0
- analyzer_plugin 0.10.0

And I tried many workaround:
- Restarting VSCode several times
- Deleting ~/.dartServer several times
- Disabling lints package
- Switching to the simplest code as possible from the tutorial

If anyone has any suggestions, I'm all ears.

**Comment by alexisbg** [comment]
@Biplab-Dutta could you please switch this issue to "Open" again ?

**Comment by Biplab-Dutta** [comment]
@alexisbg But the issue has been solved. The package is working fine on my machine.
